// <auto-generated />
using System;
using System.Collections.Generic;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260203172409_MigrationExternalFetch1")]
    partial class MigrationExternalFetch1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AFeatureAbilityValue", b =>
                {
                    b.Property<int>("AFeatureId")
                        .HasColumnType("integer");

                    b.Property<int>("AbilityIncreasesId")
                        .HasColumnType("integer");

                    b.HasKey("AFeatureId", "AbilityIncreasesId");

                    b.HasIndex("AbilityIncreasesId");

                    b.ToTable("AbilityIncreases", (string)null);
                });

            modelBuilder.Entity("AFeatureSpell", b =>
                {
                    b.Property<int>("AFeatureId")
                        .HasColumnType("integer");

                    b.Property<int>("SpellsGainedId")
                        .HasColumnType("integer");

                    b.HasKey("AFeatureId", "SpellsGainedId");

                    b.HasIndex("SpellsGainedId");

                    b.ToTable("SpellsGained", (string)null);
                });

            modelBuilder.Entity("AbilityValueCharacter", b =>
                {
                    b.Property<int>("AbilityScoresId")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.HasKey("AbilityScoresId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterAbilityScores", (string)null);
                });

            modelBuilder.Entity("CharacterSpell", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("ReadySpellsId")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "ReadySpellsId");

                    b.HasIndex("ReadySpellsId");

                    b.ToTable("CharacterSpells", (string)null);
                });

            modelBuilder.Entity("ClassSpell", b =>
                {
                    b.Property<int>("ClassesId")
                        .HasColumnType("integer");

                    b.Property<int>("SpellId")
                        .HasColumnType("integer");

                    b.HasKey("ClassesId", "SpellId");

                    b.HasIndex("SpellId");

                    b.ToTable("SpellClasses", (string)null);
                });

            modelBuilder.Entity("Api.Models.Characters.AClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("HitDie")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHomebrew")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpellcastingAbility")
                        .HasColumnType("text");

                    b.Property<int?>("SpellcastingAbilityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AClass");

                    b.HasDiscriminator().HasValue("AClass");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Api.Models.Characters.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AFeatureId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AFeatureId");

                    b.ToTable("AbilityScores", (string)null);
                });

            modelBuilder.Entity("Api.Models.Characters.AbilityValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbilityId")
                        .HasColumnType("integer");

                    b.Property<int?>("AbilityIncreaseChoiceId")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("AbilityIncreaseChoiceId");

                    b.ToTable("AbilityValues");
                });

            modelBuilder.Entity("Api.Models.Characters.Background", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHomebrew")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Backgrounds");
                });

            modelBuilder.Entity("Api.Models.Characters.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BackgroundId")
                        .HasColumnType("integer");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("CurrentSpellSlots")
                        .HasColumnType("integer[]");

                    b.Property<int?>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("InventoryId")
                        .HasColumnType("integer");

                    b.Property<int>("InventoryId1")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProficiencyBonus")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubClassId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubraceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundId");

                    b.HasIndex("ClassId");

                    b.HasIndex("InventoryId1");

                    b.HasIndex("RaceId");

                    b.HasIndex("SubClassId");

                    b.HasIndex("SubraceId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Api.Models.Characters.ClassLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantripsKnown")
                        .HasColumnType("integer");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("ProficiencyBonus")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("SpellSlots")
                        .HasColumnType("integer[]");

                    b.Property<int>("SpellsKnown")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("ClassLevels");
                });

            modelBuilder.Entity("Api.Models.Characters.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AFeatureId")
                        .HasColumnType("integer");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsExotic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHomebrew")
                        .HasColumnType("boolean");

                    b.Property<int?>("LanguageChoiceId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Script")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("TypicalSpeakers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("AFeatureId");

                    b.HasIndex("LanguageChoiceId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Api.Models.Characters.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AFeatureId")
                        .HasColumnType("integer");

                    b.Property<int>("AbilityId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHomebrew")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SkillProficiencyChoiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AFeatureId");

                    b.HasIndex("AbilityId");

                    b.HasIndex("SkillProficiencyChoiceId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Api.Models.Characters.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<bool>("IsHomebrew")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasDiscriminator().HasValue("Species");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Api.Models.Features.AFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string[]>("ArmorProficiencies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("BackgroundId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("DamageImmunityGained")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("DamageResistanceGained")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("DamageWeaknessGained")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<bool>("IsHomebrew")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("ToolProficiencies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("WeaponCategoryProficiencies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("WeaponTypeProficiencies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundId");

                    b.ToTable("AFeature");

                    b.HasDiscriminator().HasValue("AFeature");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Api.Models.Features.AbilityIncreaseChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("AbilityIncreaseChoices");
                });

            modelBuilder.Entity("Api.Models.Features.ArmorProficiencyChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Options")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("ArmorProficiencyChoices");
                });

            modelBuilder.Entity("Api.Models.Features.LanguageChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("LanguageChoices");
                });

            modelBuilder.Entity("Api.Models.Features.SkillProficiencyChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("SkillProficiencyChoices");
                });

            modelBuilder.Entity("Api.Models.Features.ToolProficiencyChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Options")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("ToolProficiencyChoices");
                });

            modelBuilder.Entity("Api.Models.Features.WeaponCategoryProficiencyChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Options")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("WeaponCategoryProficiencyChoices");
                });

            modelBuilder.Entity("Api.Models.Features.WeaponTypeProficiencyChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Options")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("WeaponTypeProficiencyChoices");
                });

            modelBuilder.Entity("Api.Models.Items.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttunedItems")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWeight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Api.Models.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BackgroundId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Categories")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("ClassId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int?>("InventoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHomebrew")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Rarity")
                        .HasColumnType("text");

                    b.Property<bool>("RequiresAttunement")
                        .HasColumnType("boolean");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundId");

                    b.HasIndex("ClassId");

                    b.HasIndex("InventoryId");

                    b.ToTable("Items");

                    b.HasDiscriminator().HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Api.Models.Spells.Spell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CastingTimeValue")
                        .HasColumnType("integer");

                    b.Property<string>("DamageRoll")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("DamageTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationValue")
                        .HasColumnType("integer");

                    b.Property<string>("EffectsAtHigherLevels")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHomebrew")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("MagicSchool")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReactionCondition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("SpellTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("Api.Models.World.Alignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Alignments");
                });

            modelBuilder.Entity("Api.Models.Characters.Class", b =>
                {
                    b.HasBaseType("Api.Models.Characters.AClass");

                    b.HasDiscriminator().HasValue("Class");
                });

            modelBuilder.Entity("Api.Models.Characters.Subclass", b =>
                {
                    b.HasBaseType("Api.Models.Characters.AClass");

                    b.Property<int>("ParentClassId")
                        .HasColumnType("integer");

                    b.HasIndex("ParentClassId");

                    b.HasDiscriminator().HasValue("Subclass");
                });

            modelBuilder.Entity("Api.Models.Characters.Race", b =>
                {
                    b.HasBaseType("Api.Models.Characters.Species");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("integer");

                    b.HasIndex("CharacterId");

                    b.HasDiscriminator().HasValue("Race");
                });

            modelBuilder.Entity("Api.Models.Characters.Subrace", b =>
                {
                    b.HasBaseType("Api.Models.Characters.Species");

                    b.Property<int>("ParentRaceId")
                        .HasColumnType("integer");

                    b.HasIndex("ParentRaceId");

                    b.HasDiscriminator().HasValue("Subrace");
                });

            modelBuilder.Entity("Api.Models.Features.BackgroundFeature", b =>
                {
                    b.HasBaseType("Api.Models.Features.AFeature");

                    b.Property<int>("BackgroundId1")
                        .HasColumnType("integer");

                    b.HasIndex("BackgroundId1");

                    b.HasDiscriminator().HasValue("BackgroundFeature");
                });

            modelBuilder.Entity("Api.Models.Features.ClassFeature", b =>
                {
                    b.HasBaseType("Api.Models.Features.AFeature");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.HasIndex("LevelId");

                    b.HasDiscriminator().HasValue("ClassFeature");
                });

            modelBuilder.Entity("Api.Models.Features.Feat", b =>
                {
                    b.HasBaseType("Api.Models.Features.AFeature");

                    b.Property<int?>("FromBackgroundId")
                        .HasColumnType("integer");

                    b.Property<int?>("FromClassId")
                        .HasColumnType("integer");

                    b.Property<int?>("FromRaceId")
                        .HasColumnType("integer");

                    b.Property<string>("Prerequisite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("FromBackgroundId");

                    b.HasIndex("FromClassId");

                    b.HasIndex("FromRaceId");

                    b.HasDiscriminator().HasValue("Feat");
                });

            modelBuilder.Entity("Api.Models.Features.Trait", b =>
                {
                    b.HasBaseType("Api.Models.Features.AFeature");

                    b.Property<int>("FromRaceId")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.HasIndex("FromRaceId");

                    b.ToTable("AFeature", t =>
                        {
                            t.Property("FromRaceId")
                                .HasColumnName("Trait_FromRaceId");
                        });

                    b.HasDiscriminator().HasValue("Trait");
                });

            modelBuilder.Entity("Api.Models.Items.Armor", b =>
                {
                    b.HasBaseType("Api.Models.Items.Item");

                    b.Property<string>("ArmorCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BaseArmorClass")
                        .HasColumnType("integer");

                    b.Property<int?>("ModCap")
                        .HasColumnType("integer");

                    b.Property<bool>("PlusDexMod")
                        .HasColumnType("boolean");

                    b.Property<bool>("StealthDisadvantage")
                        .HasColumnType("boolean");

                    b.Property<int?>("StrengthScoreRequired")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Armor");
                });

            modelBuilder.Entity("Api.Models.Items.Tool", b =>
                {
                    b.HasBaseType("Api.Models.Items.Item");

                    b.Property<string>("ToolType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Tool");
                });

            modelBuilder.Entity("Api.Models.Items.Weapon", b =>
                {
                    b.HasBaseType("Api.Models.Items.Item");

                    b.Property<string>("DamageDice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("DamageTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("LongRange")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Properties")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Range")
                        .HasColumnType("integer");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VersatileDamageDice")
                        .HasColumnType("text");

                    b.Property<string>("WeaponCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeaponType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("AFeatureAbilityValue", b =>
                {
                    b.HasOne("Api.Models.Features.AFeature", null)
                        .WithMany()
                        .HasForeignKey("AFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Characters.AbilityValue", null)
                        .WithMany()
                        .HasForeignKey("AbilityIncreasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AFeatureSpell", b =>
                {
                    b.HasOne("Api.Models.Features.AFeature", null)
                        .WithMany()
                        .HasForeignKey("AFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Spells.Spell", null)
                        .WithMany()
                        .HasForeignKey("SpellsGainedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AbilityValueCharacter", b =>
                {
                    b.HasOne("Api.Models.Characters.AbilityValue", null)
                        .WithMany()
                        .HasForeignKey("AbilityScoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSpell", b =>
                {
                    b.HasOne("Api.Models.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Spells.Spell", null)
                        .WithMany()
                        .HasForeignKey("ReadySpellsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassSpell", b =>
                {
                    b.HasOne("Api.Models.Characters.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Spells.Spell", null)
                        .WithMany()
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Models.Characters.Ability", b =>
                {
                    b.HasOne("Api.Models.Features.AFeature", null)
                        .WithMany("SavingThrowProficiencies")
                        .HasForeignKey("AFeatureId");
                });

            modelBuilder.Entity("Api.Models.Characters.AbilityValue", b =>
                {
                    b.HasOne("Api.Models.Characters.Ability", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Features.AbilityIncreaseChoice", null)
                        .WithMany("Options")
                        .HasForeignKey("AbilityIncreaseChoiceId");

                    b.Navigation("Ability");
                });

            modelBuilder.Entity("Api.Models.Characters.Background", b =>
                {
                    b.OwnsOne("Api.Models.Items.Currency", "StartingCurrency", b1 =>
                        {
                            b1.Property<int>("BackgroundId")
                                .HasColumnType("integer");

                            b1.Property<int>("Brass")
                                .HasColumnType("integer");

                            b1.Property<int>("Copper")
                                .HasColumnType("integer");

                            b1.Property<int>("Electrum")
                                .HasColumnType("integer");

                            b1.Property<int>("Gold")
                                .HasColumnType("integer");

                            b1.Property<int>("Platinum")
                                .HasColumnType("integer");

                            b1.Property<int>("Silver")
                                .HasColumnType("integer");

                            b1.HasKey("BackgroundId");

                            b1.ToTable("Backgrounds");

                            b1.WithOwner()
                                .HasForeignKey("BackgroundId");
                        });

                    b.OwnsMany("Api.Models.Characters.StartingItemOption", "StartingItemsOptions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("BackgroundId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.PrimitiveCollection<int[]>("ItemOptionIds")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.HasKey("Id");

                            b1.HasIndex("BackgroundId");

                            b1.ToTable("StartingItemOption");

                            b1.WithOwner()
                                .HasForeignKey("BackgroundId");
                        });

                    b.Navigation("StartingCurrency")
                        .IsRequired();

                    b.Navigation("StartingItemsOptions");
                });

            modelBuilder.Entity("Api.Models.Characters.Character", b =>
                {
                    b.HasOne("Api.Models.Characters.Background", "Background")
                        .WithMany()
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Characters.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Items.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Characters.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Characters.Subclass", "SubClass")
                        .WithMany()
                        .HasForeignKey("SubClassId");

                    b.HasOne("Api.Models.Characters.Subrace", "Subrace")
                        .WithMany()
                        .HasForeignKey("SubraceId");

                    b.OwnsMany("Api.Models.Characters.ArmorProficiency", "ArmorProficiencies", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("ArmorType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("FeatureId")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterId", "__synthesizedOrdinal");

                            b1.ToTable("Characters");

                            b1.ToJson("ArmorProficiencies");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsMany("Api.Models.Characters.ClassSpecificSlot", "CurrentClassSlots", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterId", "Id");

                            b1.ToTable("Characters_CurrentClassSlots");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("Api.Models.Characters.CharacterDescription", "CharacterDescription", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int?>("Age")
                                .HasColumnType("integer");

                            b1.Property<int?>("AlignmentId")
                                .HasColumnType("integer");

                            b1.Property<string>("AlliesAndOrganizations")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Backstory")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Bonds")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CharacterPictureUrl")
                                .HasColumnType("text");

                            b1.Property<string>("Eyes")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Flaws")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Hair")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int?>("Height")
                                .HasColumnType("integer");

                            b1.Property<string>("Ideals")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PersonalityTraits")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Skin")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int?>("Weight")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("Api.Models.Characters.CombatStats", "CombatStats", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int>("ArmorClass")
                                .HasColumnType("integer");

                            b1.Property<int>("CurrentHP")
                                .HasColumnType("integer");

                            b1.Property<int>("CurrentHitDice")
                                .HasColumnType("integer");

                            b1.Property<int>("Initiative")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxHP")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxHitDice")
                                .HasColumnType("integer");

                            b1.Property<int>("Speed")
                                .HasColumnType("integer");

                            b1.Property<int>("TempHP")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsMany("Api.Models.Characters.DamageAffinity", "DamageAffinities", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("AffinityType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("DamageType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("FeatureId")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterId", "__synthesizedOrdinal");

                            b1.ToTable("Characters");

                            b1.ToJson("DamageAffinities");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsMany("Api.Models.Characters.LanguageProficiency", "Languages", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("FeatureId")
                                .HasColumnType("integer");

                            b1.Property<int>("LanguageId")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterId", "__synthesizedOrdinal");

                            b1.ToTable("Characters");

                            b1.ToJson("Languages");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsMany("Api.Models.Characters.SaveThrowProficiency", "SavingThrows", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("AbilityId")
                                .HasColumnType("integer");

                            b1.Property<int>("FeatureId")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterId", "__synthesizedOrdinal");

                            b1.ToTable("Characters");

                            b1.ToJson("SavingThrows");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsMany("Api.Models.Characters.SkillProficiency", "SkillProficiencies", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("FeatureId")
                                .HasColumnType("integer");

                            b1.Property<bool>("HasExpertise")
                                .HasColumnType("boolean");

                            b1.Property<int>("SkillId")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterId", "__synthesizedOrdinal");

                            b1.ToTable("Characters");

                            b1.ToJson("SkillProficiencies");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsMany("Api.Models.Characters.ToolProficiency", "ToolProficiencies", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("FeatureId")
                                .HasColumnType("integer");

                            b1.Property<string>("ToolType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CharacterId", "__synthesizedOrdinal");

                            b1.ToTable("Characters");

                            b1.ToJson("ToolProficiencies");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsMany("Api.Models.Characters.WeaponCategoryProficiency", "WeaponCategoryProficiencies", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("FeatureId")
                                .HasColumnType("integer");

                            b1.Property<string>("WeaponCategory")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CharacterId", "__synthesizedOrdinal");

                            b1.ToTable("Characters");

                            b1.ToJson("WeaponCategoryProficiencies");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsMany("Api.Models.Characters.WeaponTypeProficiency", "WeaponTypeProficiencies", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("integer");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("FeatureId")
                                .HasColumnType("integer");

                            b1.Property<string>("WeaponType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CharacterId", "__synthesizedOrdinal");

                            b1.ToTable("Characters");

                            b1.ToJson("WeaponTypeProficiencies");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("ArmorProficiencies");

                    b.Navigation("Background");

                    b.Navigation("CharacterDescription")
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("CombatStats")
                        .IsRequired();

                    b.Navigation("CurrentClassSlots");

                    b.Navigation("DamageAffinities");

                    b.Navigation("Inventory");

                    b.Navigation("Languages");

                    b.Navigation("Race");

                    b.Navigation("SavingThrows");

                    b.Navigation("SkillProficiencies");

                    b.Navigation("SubClass");

                    b.Navigation("Subrace");

                    b.Navigation("ToolProficiencies");

                    b.Navigation("WeaponCategoryProficiencies");

                    b.Navigation("WeaponTypeProficiencies");
                });

            modelBuilder.Entity("Api.Models.Characters.ClassLevel", b =>
                {
                    b.HasOne("Api.Models.Characters.AClass", "Class")
                        .WithMany("ClassLevels")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Api.Models.Characters.ClassSpecificSlot", "ClassSpecificSlotsAtLevel", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("ClassLevelId")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("ClassLevelId");

                            b1.ToTable("ClassLevels_ClassSpecificSlotsAtLevel");

                            b1.WithOwner()
                                .HasForeignKey("ClassLevelId");
                        });

                    b.Navigation("Class");

                    b.Navigation("ClassSpecificSlotsAtLevel");
                });

            modelBuilder.Entity("Api.Models.Characters.Language", b =>
                {
                    b.HasOne("Api.Models.Features.AFeature", null)
                        .WithMany("Languages")
                        .HasForeignKey("AFeatureId");

                    b.HasOne("Api.Models.Features.LanguageChoice", null)
                        .WithMany("Options")
                        .HasForeignKey("LanguageChoiceId");
                });

            modelBuilder.Entity("Api.Models.Characters.Skill", b =>
                {
                    b.HasOne("Api.Models.Features.AFeature", null)
                        .WithMany("SkillProficiencies")
                        .HasForeignKey("AFeatureId");

                    b.HasOne("Api.Models.Characters.Ability", "Ability")
                        .WithMany("Skills")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Features.SkillProficiencyChoice", null)
                        .WithMany("Options")
                        .HasForeignKey("SkillProficiencyChoiceId");

                    b.Navigation("Ability");
                });

            modelBuilder.Entity("Api.Models.Characters.Species", b =>
                {
                    b.OwnsOne("Api.Models.Characters.RaceDescription", "RaceDescription", b1 =>
                        {
                            b1.Property<int>("SpeciesId")
                                .HasColumnType("integer");

                            b1.Property<string>("Aging")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CommonAlignment")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("General")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Languages")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Size")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SpeciesId");

                            b1.ToTable("Species");

                            b1.WithOwner()
                                .HasForeignKey("SpeciesId");
                        });

                    b.Navigation("RaceDescription")
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Models.Features.AFeature", b =>
                {
                    b.HasOne("Api.Models.Characters.Background", null)
                        .WithMany("Features")
                        .HasForeignKey("BackgroundId");
                });

            modelBuilder.Entity("Api.Models.Features.AbilityIncreaseChoice", b =>
                {
                    b.HasOne("Api.Models.Features.AFeature", null)
                        .WithMany("AbilityIncreaseChoices")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Models.Features.ArmorProficiencyChoice", b =>
                {
                    b.HasOne("Api.Models.Features.AFeature", null)
                        .WithMany("ArmorProficiencyChoices")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Models.Features.LanguageChoice", b =>
                {
                    b.HasOne("Api.Models.Features.AFeature", null)
                        .WithMany("LanguageChoices")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Models.Features.SkillProficiencyChoice", b =>
                {
                    b.HasOne("Api.Models.Features.AFeature", null)
                        .WithMany("SkillProficiencyChoices")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Models.Features.ToolProficiencyChoice", b =>
                {
                    b.HasOne("Api.Models.Features.AFeature", null)
                        .WithMany("ToolProficiencyChoices")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Models.Features.WeaponCategoryProficiencyChoice", b =>
                {
                    b.HasOne("Api.Models.Features.AFeature", null)
                        .WithMany("WeaponCategoryProficiencyChoices")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Models.Features.WeaponTypeProficiencyChoice", b =>
                {
                    b.HasOne("Api.Models.Features.AFeature", null)
                        .WithMany("WeaponTypeProficiencyChoices")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Models.Items.Inventory", b =>
                {
                    b.OwnsMany("Api.Models.Items.EquipmentSlot", "EquippedItems", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("EquipmentId")
                                .HasColumnType("integer");

                            b1.Property<string>("Slot")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("InventoryId", "Id");

                            b1.ToTable("EquipmentSlot");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("Api.Models.Items.Currency", "Currency", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("integer");

                            b1.Property<int>("Brass")
                                .HasColumnType("integer");

                            b1.Property<int>("Copper")
                                .HasColumnType("integer");

                            b1.Property<int>("Electrum")
                                .HasColumnType("integer");

                            b1.Property<int>("Gold")
                                .HasColumnType("integer");

                            b1.Property<int>("Platinum")
                                .HasColumnType("integer");

                            b1.Property<int>("Silver")
                                .HasColumnType("integer");

                            b1.HasKey("InventoryId");

                            b1.ToTable("Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.Navigation("Currency")
                        .IsRequired();

                    b.Navigation("EquippedItems");
                });

            modelBuilder.Entity("Api.Models.Items.Item", b =>
                {
                    b.HasOne("Api.Models.Characters.Background", null)
                        .WithMany("StartingItems")
                        .HasForeignKey("BackgroundId");

                    b.HasOne("Api.Models.Characters.Class", null)
                        .WithMany("StartingEquipment")
                        .HasForeignKey("ClassId");

                    b.HasOne("Api.Models.Items.Inventory", null)
                        .WithMany("StoredItems")
                        .HasForeignKey("InventoryId");
                });

            modelBuilder.Entity("Api.Models.Spells.Spell", b =>
                {
                    b.OwnsOne("Api.Models.Spells.CastingRequirements", "CastingRequirements", b1 =>
                        {
                            b1.Property<int>("SpellId")
                                .HasColumnType("integer");

                            b1.Property<int?>("MaterialCost")
                                .HasColumnType("integer");

                            b1.Property<string>("Materials")
                                .HasColumnType("text");

                            b1.Property<bool>("MaterialsConsumed")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Somatic")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Verbal")
                                .HasColumnType("boolean");

                            b1.HasKey("SpellId");

                            b1.ToTable("Spells");

                            b1.WithOwner()
                                .HasForeignKey("SpellId");
                        });

                    b.OwnsOne("Api.Models.Spells.SpellTargeting", "SpellTargeting", b1 =>
                        {
                            b1.Property<int>("SpellId")
                                .HasColumnType("integer");

                            b1.Property<string>("Range")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("RangeValue")
                                .HasColumnType("integer");

                            b1.Property<string>("ShapeLength")
                                .HasColumnType("text");

                            b1.Property<string>("ShapeType")
                                .HasColumnType("text");

                            b1.Property<string>("ShapeWidth")
                                .HasColumnType("text");

                            b1.Property<string>("TargetType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SpellId");

                            b1.ToTable("Spells");

                            b1.WithOwner()
                                .HasForeignKey("SpellId");
                        });

                    b.Navigation("CastingRequirements")
                        .IsRequired();

                    b.Navigation("SpellTargeting")
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Models.Characters.Class", b =>
                {
                    b.OwnsMany("Api.Models.Characters.StartingEquipmentChoice", "StartingEquipmentChoices", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("ClassId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int?>("NumberOfChoices")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("ClassId");

                            b1.ToTable("StartingEquipmentChoice");

                            b1.WithOwner()
                                .HasForeignKey("ClassId");

                            b1.OwnsMany("Api.Models.Characters.StartingEquipmentOption", "Options", b2 =>
                                {
                                    b2.Property<int>("StartingEquipmentChoiceId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("AnyOfArmorCategory")
                                        .HasColumnType("text");

                                    b2.Property<string>("AnyOfWeaponCategory")
                                        .HasColumnType("text");

                                    b2.Property<string>("AnyOfWeaponType")
                                        .HasColumnType("text");

                                    b2.Property<int?>("EquipmentId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Quantity")
                                        .HasColumnType("integer");

                                    b2.HasKey("StartingEquipmentChoiceId", "Id");

                                    b2.HasIndex("EquipmentId");

                                    b2.ToTable("StartingEquipmentOption");

                                    b2.HasOne("Api.Models.Items.Item", "Equipment")
                                        .WithMany()
                                        .HasForeignKey("EquipmentId");

                                    b2.WithOwner()
                                        .HasForeignKey("StartingEquipmentChoiceId");

                                    b2.Navigation("Equipment");
                                });

                            b1.Navigation("Options");
                        });

                    b.Navigation("StartingEquipmentChoices");
                });

            modelBuilder.Entity("Api.Models.Characters.Subclass", b =>
                {
                    b.HasOne("Api.Models.Characters.Class", "ParentClass")
                        .WithMany("Subclasses")
                        .HasForeignKey("ParentClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentClass");
                });

            modelBuilder.Entity("Api.Models.Characters.Race", b =>
                {
                    b.HasOne("Api.Models.Characters.Character", null)
                        .WithMany("OtherRaces")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("Api.Models.Characters.Subrace", b =>
                {
                    b.HasOne("Api.Models.Characters.Race", "ParentRace")
                        .WithMany("SubRaces")
                        .HasForeignKey("ParentRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentRace");
                });

            modelBuilder.Entity("Api.Models.Features.BackgroundFeature", b =>
                {
                    b.HasOne("Api.Models.Characters.Background", "Background")
                        .WithMany()
                        .HasForeignKey("BackgroundId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Background");
                });

            modelBuilder.Entity("Api.Models.Features.ClassFeature", b =>
                {
                    b.HasOne("Api.Models.Characters.ClassLevel", "Level")
                        .WithMany("NewFeatures")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("Api.Models.Features.Feat", b =>
                {
                    b.HasOne("Api.Models.Characters.Background", "FromBackground")
                        .WithMany()
                        .HasForeignKey("FromBackgroundId");

                    b.HasOne("Api.Models.Characters.Class", "FromClass")
                        .WithMany()
                        .HasForeignKey("FromClassId");

                    b.HasOne("Api.Models.Characters.Race", "FromRace")
                        .WithMany()
                        .HasForeignKey("FromRaceId");

                    b.Navigation("FromBackground");

                    b.Navigation("FromClass");

                    b.Navigation("FromRace");
                });

            modelBuilder.Entity("Api.Models.Features.Trait", b =>
                {
                    b.HasOne("Api.Models.Characters.Species", "FromRace")
                        .WithMany("Traits")
                        .HasForeignKey("FromRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromRace");
                });

            modelBuilder.Entity("Api.Models.Items.Tool", b =>
                {
                    b.OwnsMany("Api.Models.Items.ToolActivity", "Activities", b1 =>
                        {
                            b1.Property<int>("ToolId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("AbilityId")
                                .HasColumnType("integer");

                            b1.Property<string>("DC")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int?>("SkillId")
                                .HasColumnType("integer");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ToolId", "Id");

                            b1.ToTable("ToolActivity");

                            b1.WithOwner()
                                .HasForeignKey("ToolId");
                        });

                    b.OwnsMany("Api.Models.Items.ToolProperty", "Properties", b1 =>
                        {
                            b1.Property<int>("ToolId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ToolId", "Id");

                            b1.ToTable("ToolProperty");

                            b1.WithOwner()
                                .HasForeignKey("ToolId");
                        });

                    b.Navigation("Activities");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Api.Models.Characters.AClass", b =>
                {
                    b.Navigation("ClassLevels");
                });

            modelBuilder.Entity("Api.Models.Characters.Ability", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Api.Models.Characters.Background", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("StartingItems");
                });

            modelBuilder.Entity("Api.Models.Characters.Character", b =>
                {
                    b.Navigation("OtherRaces");
                });

            modelBuilder.Entity("Api.Models.Characters.ClassLevel", b =>
                {
                    b.Navigation("NewFeatures");
                });

            modelBuilder.Entity("Api.Models.Characters.Species", b =>
                {
                    b.Navigation("Traits");
                });

            modelBuilder.Entity("Api.Models.Features.AFeature", b =>
                {
                    b.Navigation("AbilityIncreaseChoices");

                    b.Navigation("ArmorProficiencyChoices");

                    b.Navigation("LanguageChoices");

                    b.Navigation("Languages");

                    b.Navigation("SavingThrowProficiencies");

                    b.Navigation("SkillProficiencies");

                    b.Navigation("SkillProficiencyChoices");

                    b.Navigation("ToolProficiencyChoices");

                    b.Navigation("WeaponCategoryProficiencyChoices");

                    b.Navigation("WeaponTypeProficiencyChoices");
                });

            modelBuilder.Entity("Api.Models.Features.AbilityIncreaseChoice", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Api.Models.Features.LanguageChoice", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Api.Models.Features.SkillProficiencyChoice", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Api.Models.Items.Inventory", b =>
                {
                    b.Navigation("StoredItems");
                });

            modelBuilder.Entity("Api.Models.Characters.Class", b =>
                {
                    b.Navigation("StartingEquipment");

                    b.Navigation("Subclasses");
                });

            modelBuilder.Entity("Api.Models.Characters.Race", b =>
                {
                    b.Navigation("SubRaces");
                });
#pragma warning restore 612, 618
        }
    }
}
